export const VS_OK = "OK";
export const VS_WARN = "WARN";
export const VS_FAIL = "FAIL";

export const ALL_VALIDATION_STATUS = [
    VS_OK,
    VS_WARN,
    VS_FAIL
];

export const VR_APPROVAL_ACCEPTED = "APPROVAL_ACCEPTED";
export const VR_ALREADY_APPROVED = "ALREADY_APPROVED";
export const VR_IPV6_DETECTED = "IPV6_DETECTED";
export const VR_BLOCKING_DEVICE_OFFLINE = "BLOCKING_DEVICE_OFFLINE";
export const VR_AGREEMENT_MISSING = "AGREEMENT_MISSING";
export const VR_APPROVAL_DENIED = "APPROVAL_DENIED";
export const VR_APPROVAL_PENDING = "APPROVAL_PENDING";
export const VR_NETWORK_NOT_PRIVATE = "NETWORK_NOT_PRIVATE";
export const VR_INVALID_ACCOUNT_TYPE = "INVALID_ACCOUNT_TYPE";
export const VR_NETWORK_CONTEXT_MISSING = "NETWORK_CONTEXT_MISSING";

export const ALL_VALIDATION_REASON = [
    VR_APPROVAL_ACCEPTED,
    VR_ALREADY_APPROVED,
    VR_IPV6_DETECTED,
    VR_BLOCKING_DEVICE_OFFLINE,
    VR_AGREEMENT_MISSING,
    VR_APPROVAL_DENIED,
    VR_APPROVAL_PENDING,
    VR_NETWORK_NOT_PRIVATE,
    VR_INVALID_ACCOUNT_TYPE,
    VR_NETWORK_CONTEXT_MISSING
];

export const ALL_VALIDATION_REASON_OK = [
    VR_APPROVAL_ACCEPTED,
    VR_ALREADY_APPROVED
];

export const ALL_VALIDATION_REASON_WARN = [
    VR_IPV6_DETECTED,
    VR_BLOCKING_DEVICE_OFFLINE
];

export const ALL_VALIDATION_REASON_FAIL = [
    VR_AGREEMENT_MISSING,
    VR_APPROVAL_DENIED,
    VR_APPROVAL_PENDING,
    VR_NETWORK_NOT_PRIVATE,
    VR_INVALID_ACCOUNT_TYPE,
    VR_NETWORK_CONTEXT_MISSING
];


